# =============================================================================
# SRAL Local Developer Configuration Overrides (developer_input.ini)
# =============================================================================

# Absolute path tracking the active Emscripten WebAssembly SDK location
emsdk_install = C:/tools/emsdk

# Absolute folder location addressing the local Google Android NDK workspace tree
android_ndk   = C:/Users/Sheryl/AppData/Local/Android/Sdk/ndk/29.0.14206865
